package SeleniumBasics;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;


import java.util.HashMap;
import java.util.List;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Map;
public class MyFirstSeleniumExample {
	WebDriver driver;
	
	@BeforeClass
	public void PrepareManulascenario() {
		System.out.println("Prepare Manual Test Case.!!");
	}
	
	@Test(priority=1)
	public void Setup() {
		// Generated by Selenium IDE
				System.setProperty("webdriver.chrome.driver", "C:\\chromeDriver\\chromedriver_win32.exe");
			WebDriver	driver =new ChromeDriver();
				driver.get("https://www.seleniumhq.org/");
		
	}
	@Test(priority=2)
	public void TC_NavigateToAboutPage_SeleniumHQApp(){
	
		

		    driver.findElement(By.linkText("Documentation")).click();
		    driver.findElement(By.cssSelector("li:nth-child(2) > input")).click();
		    driver.findElement(By.linkText("About")).click();

		
		
	}
@Test(priority=3)

public void tearDown() {
	driver.close();
	driver.quit();}
}





